name: Package and release development builds

on:
    push:
        tags:
            - "v*.*.*-*"
            - "v*.*-*"
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest

        env:
            CF_API_KEY: ${{ secrets.CF_API_KEY }}
            WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
            WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
            GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

        steps:
            - name: Clone project
              uses: actions/checkout@v1

            - name: Package and release for Classic
              uses: BigWigsMods/packager@master
              with:
                  args: -g classic -w 0

            - name: Package and release for Cata
              uses: BigWigsMods/packager@master
              with:
                  args: -g cata -w 0

            - name: Package and release for Retail
              uses: BigWigsMods/packager@master
              with:
                  args: -g retail -w 0
